# Local development services.
#
# To activate this feature, follow the instructions at the top of the
# 'example.settings.local.php' file, which sits next to this file.
parameters:
  twig.config:
    debug: true
    cache: false
    auto_reload: true
