<?php

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_theme().
 */
function airc_theme($existing, $type, $theme, $path) {
  return [
    'content-listing' => [
      'varibles' => ['content' => NULL],
    ]

  ];
}

// function airc_cron() {
//   \Drupal::messenger()->addMessage(t("Hello from mymodule cron hook"));
// }

// function airc_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
//   if ($form_id == 'node_article_edit_form') {
//     $form['actions']['submit']['#value'] = t("Save this awesome article!");
//   }
// }
